<a href="https://colab.research.google.com/github/sharmi510/Data-Mining/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

math = np.array([88, 76, 95, 65, 82, 91, 70, 88, 55, 92])

print(math)

[88 76 95 65 82 91 70 88 55 92]


In [2]:
print("Mean:", np.mean(math))
print("Median:", np.median(math))
print("Standard deviation:", np.std(math))
print("Maximum:", np.max(math))
print("Minimum:", np.min(math))

Mean: 80.2
Median: 85.0
Standard deviation: 12.600000000000001
Maximum: 95
Minimum: 55


We can put Maths, Science and English marks into one array.

Each row-> one student
each coloumn-> subjects (Maths, English, Science)

In [5]:
marks = np.array([
    [88, 92, 85],
    [76, 81, 90],
    [95, 89, 88],
    [65, 70, 78],
    [82, 85, 80],
    [91, 94, 92],
    [70, 68, 72],
    [88, 82, 75],
    [55, 60, 68],
    [92, 95, 90]
])

axis = 1 -> each student/row

In [7]:
np.sum(marks, axis=1)

array([265, 247, 272, 213, 247, 277, 210, 245, 183, 277])

axis = 0 -> each subject/coloumn

In [8]:
np.mean(marks, axis=0)

array([80.2, 81.6, 81.8])

np.where() allows us to make a decision based on a condition.

In [10]:
print(len(np.where(math > 80)[0]))

6


Ann had 55 marks in maths
and the array before [88 76 95 65 82 91 70 88 55 92]

In [11]:
new_math = np.where(math < 60, math + 5, math)

print(new_math)

[88 76 95 65 82 91 70 88 60 92]


Do more study hours relate to higher Maths marks?

0 -> first row (study hours)
1 -> second column (maths)

In [14]:
study_hours = np.array([14,8,18,5,10,16,6,7,2,8])

In [15]:
correlation = np.corrcoef(study_hours, math)[0, 1]

print(correlation)

0.8101275328459048
